# This is a basic workflow to help you get started with Actions

name: Cloud Automation webhooks

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - silent
      - interactive        
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: show client_payload
      if: github.event.action == 'silent'
      run: |
        echo "Received silent webhook, just displaying data"
        echo "type": "${{ github.event.client_payload.type }}"
        echo "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}"
        echo "triggeredid": "${{ github.event.client_payload.id }}"
    - name: Simulate processsing
      if: github.event.action == 'interactive'
      run: sleep 5
    - name: send keptn finished event
      if: github.event.action == 'interactive'
      run: |
        echo "Received interactive webhook, will send back keptn finished event"
        json=$(cat <<-END
            {
              "data": {
                "project":"demo",
                "stage":"production",
                "service":"casdemoapp",
                "status": "succeeded",
                "result": "pass", 
                "custom":"this is custom data",
                "custom1":"this is custom1 data",
                "mytask-interactive": {
                  "link": "https://a-back-link-to-result",
                  "more": "even more data"
                }
              },
              "source": "cas-quickstart",
              "specversion": "1.0",
              "type": "sh.keptn.event.mytask-interactive.finished",
              "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}",
              "triggeredid": "${{ github.event.client_payload.id }}"
            }
        END
        )
        echo "json=$json"
        curl -X POST "${{ secrets.KEPTN_API_URL }}/v1/event" -H "Content-Type: application/json" -H "accept: application/json" -H "x-token: ${{ secrets.KEPTN_API_TOKEN }}" -d "$json"
