# This is a basic workflow to help you get started with Actions

name: webhooks interactive example

# Controls when the workflow will run
on:
  repository_dispatch:
    types: 
      - interactive        
jobs:
  test:
    name: Demo interactive event
    runs-on: ubuntu-latest
    steps:
    - name: send mytask-interactive.finished event
      run: |
        echo "Received interactive webhook, will send back keptn finished event"
        json=$(cat <<-END
            {
              "data": {
                "project":"${{ github.event.client_payload.project }}",
                "stage":"${{ github.event.client_payload.stage }}",
                "service":"${{ github.event.client_payload.service }}",
                "status": "succeeded",
                "result": "pass",
                "mytask-interactive": {
                  "link": "https://a-back-link-to-result",
                  "more": "even more data"
                }
              },
              "source": "cas-quickstart",
              "specversion": "1.0",
              "type": "sh.keptn.event.mytask-interactive.finished",
              "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}",
              "triggeredid": "${{ github.event.client_payload.id }}"
            }
        END
        )
        echo "json=$json"
        curl -s -X POST "${{ secrets.KEPTN_API_URL }}/v1/event" -H "Content-Type: application/json" -H "accept: application/json" -H "x-token: ${{ secrets.KEPTN_API_TOKEN }}" -d "$json"
        echo "Complete"
