# This is a basic workflow to help you get started with Actions

name: Cloud Automation webhooks silent example

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - silent
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: show client_payload
      run: |
        echo "Received silent webhook, just displaying data"
        echo "type": "${{ github.event.client_payload.type }}"
        echo "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}"
        echo "triggeredid": "${{ github.event.client_payload.id }}"
